Repository FLAMEGPU/FLAMEGPU2-docs, pull requests merged in 2022-10, with the labels that each got.

#90 Docs update for wrapped spatial message iterator.
  src/guide/agent-functions/agent-communication.rst
  src/tutorial/index.rst
Labels: enhancement

#99 Debugging models chapter
  CMakeLists.txt
  src/guide/agent-functions/defining-agent-functions.rst
  src/guide/debugging-models/NB_MYCNx512.png
  src/guide/debugging-models/NB_cycle_stages_6x512.png
  src/guide/debugging-models/NB_living_countx512.png
  src/guide/debugging-models/NB_telo_countx512.png
  src/guide/debugging-models/index.rst
  src/guide/debugging-models/logging.rst
  src/guide/debugging-models/print.rst
  src/guide/debugging-models/seatbelts.rst
  src/guide/debugging-models/using-a-debugger.rst
  src/guide/debugging-models/visual_studio_attach_to_process_dialog.png
  src/guide/debugging-models/visual_studio_build_config.png
  src/guide/debugging-models/visual_studio_start_debugger.png
  src/guide/debugging-models/visual_studio_startup_project.png
  src/guide/index.rst
  src/guide/running-multiple-simulations/index.rst
Labels: documentation, enhancement

#116 Update 3rd party github actions to fix GHA node deprecation warnings.
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: hacktoberfest-accepted
